version: '3'
services:
  php:
    build: build/php
    working_dir: /var/www/symfony
    expose:
      - "9000"
    depends_on:
      - db
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
    environment:
        - DATABASE_URL=mysql://mydbuser:mydbuserpassword@db:3306/mywebsite
  web:
    build: build/nginx
    restart: always
    ports:
        - "81:80"
    depends_on:
        - php
        - db
    volumes:
        - ./symfony:/var/www/symfony:cached
        - ./logs/nginx:/var/log/nginx:cached
  db:
    image: mysql/mysql-server:5.7
    environment:
        - MYSQL_ROOT_PASSWORD=mypassword
        - MYSQL_ROOT_HOST=%
        - MYSQL_USER=mydbuser
        - MYSQL_PASSWORD=mydbuserpassword
        - MYSQL_DATABASE=mywebsite
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  elk:
      image: willdurand/elk
      ports:
          - "82:80"
      volumes:
          - ./build/elk/logstash:/etc/logstash:cached
          - ./build/elk/logstash/patterns:/opt/logstash/patterns:cached
          - ./logs/nginx:/var/log/nginx:cached
          - ./logs/symfony:/var/www/symfony/var/log:cached
